# Generated by Django 5.0.1 on 2024-01-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name = 'blog',
            old_name = 'updated_at',
            new_name = 'updamed_at',
        )
    ]
