# Generated by Django 5.0.1 on 2024-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updamed_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
