# Generated by Django 5.0.1 on 2024-02-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='phone',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_blogs', to='blog.author'),
        ),
    ]
